name: Deploy Docs (on latest push to main branch)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write   # for gh-pages deployment
  pages: write      # needed by deploy-pages
  id-token: write   # needed by deploy-pages OIDC

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  PYTHONIOENCODING: "utf-8"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # ------------------- ASSEMBLE -------------------
      - name: A1) Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: A2) Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: A3) Pin Python version for consistency
        run: uv python pin 3.12

      - name: A4) Sync to install dependencies
        run: uv sync --extra dev --extra docs --upgrade

      # ------------------- BASELINE CHECKS -------------------
      - name: B1) Fail fast if no MkDocs configuration
        run: |
          if [ -f "mkdocs.yml" ] || [ -f "mkdocs.yaml" ]; then
            echo "MkDocs configuration found. Proceeding."
          else
            echo "ERROR: mkdocs.yml not found."
            echo "If you do not want documentation deployment,"
            echo "delete .github/workflows/deploy-docs.yml (or add mkdocs.yml)."
            exit 1
          fi

      # ------------ DEPLOY ------------------
      - name: Verify MkDocs is installed
        run: |
          uv run mkdocs --version
          uv run python -c "import mkdocs; print('mkdocs import OK')"

      - name: D1) Build docs (mkdocs --strict)
        run: uv run mkdocs build --strict

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: D2) Assert site artifact exists
        run: |
          test -d site && test -f site/index.html || {
            echo "ERROR: MkDocs build produced no site/index.html"
            exit 1
          }

      - name: D3) Upload site as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: D4) Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
